name = "chronogrid-landing"
compatibility_date = "2024-01-01"

[env.production]
name = "chronogrid-landing"

[env.production.vars]
NODE_ENV = "production"

# Build configuration
[build]
command = "npm run build"
output = "out"

# Pages configuration
[pages]
build_output_dir = "out"
node_compat = true

# Environment variables (set these in Cloudflare dashboard)
# NEXT_PUBLIC_SUPABASE_URL
# NEXT_PUBLIC_SUPABASE_ANON_KEY